name = "fed-reg-compliance-node"
main = "src/index.js"
compatibility_date = "2026-05-01"

[vars]
PROJECT_NAME = "fed-reg-compliance-node"
PRICE = "0.05"
WALLET_ADDRESS = "0x5e4EDBD3a93d6f0aBEb4Fe93c4f660f636F2BA4d"
